### ISSUE TITLE
Credentials

### ISSUE THREAD

**Issue by yurgon** [stephenmoloney/openstex_adapters_ovh#2]
Where I can get that:

MY_APP_CLIENT_CONSUMER_KEY
MY_APP_CLIENT_TENANT_ID
MY_APP_CLIENT_USER_ID
MY_APP_CLIENT_TEMP_URL_KEY1
MY_APP_CLIENT_TEMP_URL_KEY2

thx

**Comment by stephenmoloney** [comment]
Hi!

These three come from the OVH api:

MY_APP_CLIENT_CONSUMER_KEY
MY_APP_CLIENT_TENANT_ID
MY_APP_CLIENT_USER_ID

and they can be created at the OVH website which is recommeneded, the OVH guide 
is here: https://api.ovh.com/g934.first_step_with_api

Alternatively, I have made a mix task which will do the same thing for you and alot of the 
hard work trying to do it at the OVH website:
```shell
mix ovh --login=<username-ovh> --password=<password> --appname='my_app_name'
```
See here --- https://github.com/stephenmoloney/ex_ovh/blob/master/docs/mix_task.md


For 
```
MY_APP_CLIENT_TEMP_URL_KEY1
MY_APP_CLIENT_TEMP_URL_KEY2
```
-> These are part of the swift openstack, you can create a key yourself -
Read more here ... https://console.bluemix.net/docs/services/ObjectStorage/os_tempurl.html
I'm not sure it is a hard requirement to set those keys to get started - but If you are using tempurls, it is advisable.

I have also created a function that will set the temp url ---
see https://hexdocs.pm/openstex/Openstex.Swift.V1.Helpers.html#c:set_account_temp_url_key/2
although there is not tests for that function! :fearful: 

Finally, a fully working implementation of openstex_adapters_ovh can be seen at the following two links:

https://github.com/stephenmoloney/arc_ovh/tree/master/config
https://github.com/stephenmoloney/arc_ovh/tree/master/lib/arc_ovh

I would like to make another adapter that can login with purely swift credentials - but I haven't had time to look into that yet.

Hope this gets you up and running

**Comment by yurgon** [comment]
Thank you for answer
But Im still doте understand where a I can get MY_APP_CLIENT_CONSUMER_KEY

**Comment by yurgon** [comment]
That task: mix ovh --login=<username-ovh> --password=<password> --appname='my_app_name' not works at all

**Comment by stephenmoloney** [comment]
It works for me. 
It would be better if you posted the error you have - otherwise I have no idea what problem you are having.

**Comment by stephenmoloney** [comment]
Also, worth noting is that at the end of your username you might need to attach -ovh.

For example, if my username is gg565345. The I should write:

```
mix ovh --login=gg565345-ovh --password=password --appname=my_app_name
```
This is an OVH issue -  I think they require it.

**Comment by yurgon** [comment]
Username u mean login and password to Panel https://ca.ovh.com/manager ?

**Comment by yurgon** [comment]
Thanks a lot
All works for now

**Comment by stephenmoloney** [comment]
:+1:
